import os
DATABASE_NAME = os.getenv("DATEBASE_NAME")
TABLE_NAME = os.getenv("TABLE_NAME")
AWS_REGION = os.getenv("AWS_REGION")
CRYPTO_SYMBOL = os.getenv("CRYPTO_SYMBOL")
NAMESPACE = os.getenv("NAMESPACE")
SVC = os.getenv("SVC")
ACCESS_KEY_ID = os.getenv("ACCESS_KEY_ID")
SECRET_ACCESS_KEY = os.getenv("SECRET_ACCESS_KEY")
API_URL = os.getenv("API_URL")