apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: client-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: austinloveless/client:latest
          env:
            - name: SVC
              value: server-service
            - name: NAMESPACE
              value: app
          ports:
            - containerPort: 3001

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: austinloveless/server:latest
          ports:
            - containerPort: 3002
