{
 "title": "swagger-stats dashboard",
 "description": "Swagger-Stats Main Dashboard Revision  3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (irate(api_request_total[1m]))",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^5..$\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^4..$\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (irate(api_request_total{code=~\"^2..$\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "Request rate by Method (per sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (irate(api_request_total[1m]))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 25ms, tolerated: 100ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  sum(irate(api_request_duration_milliseconds_bucket{le=\"25\",code=~\"^2..$\"}[1m]))\n+\n  (sum(irate(api_request_duration_milliseconds_bucket{le=\"100\",code=~\"^2..$\"}[1m]))/2)\n) / sum(irate(api_request_duration_milliseconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"5\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 5ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"10\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 10ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"50\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 50ms (%)"
    },
    {
     "expr": "( sum(irate(api_request_duration_milliseconds_bucket{le=\"100\"}[1m])) /  sum(irate(api_request_duration_milliseconds_count[1m])) ) * 100",
     "legendFormat": "Duration < 100ms (%)"
    }
   ]
  },
  {
   "title": "Top 3 API calls (by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total[1m])) by (path))"
    }
   ]
  },
  {
   "title": "Top 3 API Error Calls ( 5XX, by path)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(irate(api_request_total{code=~\"^5..$\"}[1m])) by (path))"
    }
   ]
  }
 ]
}